### ISSUE TITLE
Difference of PATM between code and paper

### ISSUE THREAD

**Issue by sbl1996** [ggjy/Hire-Wave-MLP.pytorch#2]
In Section 3.2 of the [paper](https://arxiv.org/pdf/2111.12294v2.pdf), the authors say that "The ﬁnal output of the block is the summation of these three branches." However, it seems that there are extra reweight and projection after the summation. Maybe this design is from CycleMLP, but not mentioned in the paper, which may cause confusion.

**Comment by ggjy** [comment]
Thanks for your kindly reminder. This design is inherited from Vision Permutator and CycleMLP, and we will mention it in the paper.
